# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On macOS with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#
# database.yml

default: &default
  adapter: postgresql
  encoding: unicode
  database: docker_rails_development
  pool: 5
  username: postgres
  password: postgres
  host: db
  port: 5432
development:
  <<: *default

test:
  <<: *default

production:
  <<: *default